apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - name: hubserver-port
      protocol: TCP
      port: 8131
      targetPort: 8131
      nodePort: 30001
    - name: gameserver-port
      protocol: TCP
      port: 8181
      targetPort: 8181
      nodePort: 30002
